### ISSUE TITLE
Titolo sezione "Fonti" poco chiaro.

### ISSUE THREAD

**Issue by sebcossu** [spaghetti-open-data/code4health-amianto#9]
Salve ragazzi,
ho notato che la sezione dei link utili sul sito si chiama "fonti" e trovo sia fuorviante, in quanto non si capisce subito che è una pagina che contiene link utili alla causa. Una persona potrebbe metterci qualche secondo prezioso in più a trovare i contatti di cui ha bisogno o addirittura pensare che non esistano. Io propongo di rinominare la sezione come "Link" o "Link utili".
Che ne pensate?

**Comment by ebergam** [comment]
@killerklown Credo tu abbia sbagliato repo. Apri l'issue in https://github.com/emergenzeHack/terremotocentro/issues

**Comment by sebcossu** [comment]
Hai ragione, mi scuso!
